version: '3.8'
services:
  express-server:
    build: ./path/to/express/server
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql-server
    depends_on:
      - redis
      - mysql-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: